### ISSUE TITLE
Крафт в системе инвентаря.

### ISSUE THREAD

**Issue by FreshWar** [VP-GAMES/InventoryEditor#1]
[FEATURE]
Было бы круто увидеть возможность крафта в инвентаре:
подбираешь рецепт, например, "рогатого шлема", кликнув на него откроется отдельный крафтовый инвентарь рецепта состоящий из двух зон "описание рецепта" и "ячейки крафта" в ячейки крафта нужно положить, для примера, два рога и обычный шлем и нажать кнопку "создать", после чего рецепт из инвентаря исчезает и заменяется скрафченным предметом.

**Comment by VP-GAMES** [comment]
Крафт в инвентаре добавлен, как крафтить в UI, можно сделать по своим личным соображениям, успеха.
