### ISSUE TITLE
Добавить описание предмета и сделать возможным доступ к свойствами предмета через InventoryManager

### ISSUE THREAD

**Issue by FreshWar** [VP-GAMES/InventoryEditor#2]
Если свойств(property) несколько, то все они отображаются друг под другом.
Кроме этого свойства нельзя вернуть с помощью InventoryManager'а
Предлагаю сделать вывод описания предмета отдельным нодом, в котором можно разместить всё описание предмета удобным для разработчика способом.

**Comment by VP-GAMES** [comment]
Привет, начал добавлять выше описанное, можете наблюдать с [этого](https://github.com/VP-GAMES/InventoryEditor/commit/40c4660ea30a4d889db70fa6bc87439483dcb259) коммита, пока без поддержки лоцализации(добавлю в следушем коммите)

**Comment by VP-GAMES** [comment]
Описание предмета добавлено, запустите игру, нажмите правую кнопку мыши на любом собраном аитеме в инвентаре, высветится описание айтема(поддерживает RichTextLabel bbcode)
InventoryManager функции для получения properties:
get_item_properties_by_name
get_item_properties
