### ISSUE TITLE
Мягкое обновление

### ISSUE THREAD

**Issue by FreshWar** [VP-GAMES/InventoryEditor#4]
С последними обновлениями я понял, что довольно сложно обновиться так, чтобы то, что я добавил (свои предметы, категории и т.п.) не слетало с обновлениями
Предлагаю изменить файловую структуру аддона:
Создать отдельную папку Inventary_save  в папке addons.
Сохранения текущих предметов юзера отдельным файлом (с возможностью вообще не сохранять вещи после выхода из игры, если это не требуется в игре) отдельным файлом должно сохраняться в этой папке.
Файлы содержащие информацию о категориях, предметах, рецептах тоже переносятся в эту папку
Ноды самих предметов тоже будет удобно хранить в этой папке.

**Comment by VP-GAMES** [comment]
Сложного ничего нет, в папке addons/inventory_editor/ находится файл InventorySave.res важно его сохранять. Желательно пользоватся к примеру [Git](https://ru.wikipedia.org/wiki/Git). Само сохраненение addons/inventory_editor/ventorySave.res, с новыми версиями InventoryEditor полностью совместимо, я за этим слежу.
